### ISSUE TITLE
Error in Show Developer Tools

### ISSUE THREAD

**Issue by mfromin** [albertinad/brackets-bower#57]
When Brackets starts I see this:

![screen shot 2015-04-29 at 9 41 13 pm](https://cloud.githubusercontent.com/assets/2193139/7406004/a36b1be8-eeb8-11e4-9961-299e4fb0d772.png)

Any idea why I get this and how I can make it stop?

**Comment by albertinad** [comment]
Hi, that is a problem related with permissions to create the extension log file.
It is removed and fixed in the new version of brackets-bower extension. I'm having issues uploading it to the brackets registry but you can manually download the [latest](https://github.com/albertinad/brackets-bower/releases/tag/v0.2.6) release zip file and drag it to the extension manager dialog to update it.

Thanks!

**Comment by mfromin** [comment]
I deployed it and get the same error:



To deploy I just deleted the old extension and copied the folder to the extensions directory and named the folder `brackets-bower`.

--Michael

**Comment by albertinad** [comment]
You're right! give me a couple of minutes and I will released a new version with the fix.
Sorry!

**Comment by albertinad** [comment]
Hi @mfromin , [this](https://github.com/albertinad/brackets-bower/releases/tag/v0.2.7) is the latest version of the extension, without the log error and a proper error handling.

Thanks!

**Comment by albertinad** [comment]
Closing issue, feel free to re-open it if the log error persists.
